<?php defined('SYSPATH') or die('No direct script access.');

return array(
  'css' => array(
    'assets/lib/bootstrap/css/bootstrap.min.css',
    'assets/lib/bootstrap/css/bootstrap-responsive.min.css',
    'assets/lib/fontawesome/css/font-awesome.css',
    'assets/css/screen.css',
  ),
  'javascript' => array(
    'assets/lib/jquery/jquery-1.8.3.min.js',
    'assets/lib/jquery/path.min.js',
    'assets/lib/bootstrap/js/bootstrap.min.js',
    'assets/lib/knockout/knockout-2.2.0.js',
    'assets/lib/knockout/knockout.mapping-2.3.4.js',
    'assets/js/App.js',
    'assets/js/Router/App.Router.js',
    'assets/js/Events/App.Events.js',
    'assets/js/Config/App.Config.js',
    'assets/js/API/App.API.Base.js',
    'assets/js/API/App.API.Marker.js',
    'assets/js/API/App.API.Route.js',
    'assets/js/Map/App.Map.js',
    'assets/js/Map/Actions/App.Map.Actions.Action.js',
    'assets/js/Map/Actions/App.Map.Actions.Default.js',
    'assets/js/Map/Actions/App.Map.Actions.Markers.js',
    'assets/js/Map/Actions/App.Map.Actions.Routes.js',
    'assets/js/Map/Actions/App.Map.Actions.Search.js',
    'assets/js/Map/Actions/App.Map.Actions.Share.js',
    'assets/js/Map/Actions/App.Map.Actions.View.js',
    'assets/js/Controllers/App.Controllers.Map.js',
    'assets/js/Controllers/App.Controllers.SignIn.js',
    'assets/js/UI/App.UI.Device.js',
    'assets/js/UI/App.UI.Toolbar.js',
    'assets/js/UI/App.UI.Modal.js',
    'assets/js/UI/App.UI.Search.js',
    'assets/js/Models/App.Models.Base.js',
    'assets/js/Models/App.Models.Route.js',
    'assets/js/Models/App.Models.ToolbarButton.js',
    'assets/js/Models/App.Models.Marker.js',
    'assets/js/ViewModels/App.ViewModels.Toolbar.js',
    'assets/js/ViewModels/App.ViewModels.Modal.js',
    'assets/js/ViewModels/App.ViewModels.Search.js',
    'assets/js/Map/App.Map.Marker.js',
    'assets/js/Map/App.Map.Route.js',
    'assets/js/Map/App.Map.InfoWindow.js'
  ),
);